// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {ForkBase} from "./UmbraRouter.t.sol";
import {IERC20} from "../src/interfaces/Interfaces.sol";

/// End-to-end backtest: executes REAL engine routes (calldata generated by the
/// Rust `gen_fixtures` test) against the live fork and asserts the realized output
/// matches the engine's quote. Run the generator first:
///   cargo test -p umbra-core --test gen_fixtures -- --ignored
contract RouteBacktest is ForkBase {
    // recipient baked into the generated calldata (see gen_fixtures.rs)
    address constant RECIPIENT = 0x000000000000000000000000000000000000bEEF;

    function test_backtest_real_engine_routes() public {
        string memory json = vm.readFile("./test/fixtures/routes.json");
        uint256 count = vm.parseJsonUint(json, ".count");
        require(count > 0, "no fixtures; run gen_fixtures first");

        uint256 passed;
        for (uint256 i = 0; i < count; i++) {
            string memory b = string.concat(".cases[", vm.toString(i), "]");
            address tokenOut = vm.parseJsonAddress(json, string.concat(b, ".tokenOut"));
            uint256 amountIn = vm.parseJsonUint(json, string.concat(b, ".amountIn"));
            uint256 value = vm.parseJsonUint(json, string.concat(b, ".value"));
            uint256 minOut = vm.parseJsonUint(json, string.concat(b, ".minOut"));
            uint256 expected = vm.parseJsonUint(json, string.concat(b, ".expectedOut"));
            bytes memory cd = vm.parseJsonBytes(json, string.concat(b, ".calldata"));
            string memory label = vm.parseJsonString(json, string.concat(b, ".label"));

            // fund the caller with native PLS and execute the real route
            vm.deal(address(this), value);
            uint256 before = IERC20(tokenOut).balanceOf(RECIPIENT);
            (bool ok,) = address(router).call{value: value}(cd);
            require(ok, string.concat("execute reverted: ", label));
            uint256 realized = IERC20(tokenOut).balanceOf(RECIPIENT) - before;

            // realized must clear the floor and land within 3% of the engine's quote
            assertGe(realized, minOut, string.concat("below minOut: ", label));
            assertGe(realized, (expected * 97) / 100, string.concat("too low vs quote: ", label));
            assertLe(realized, (expected * 103) / 100, string.concat("too high vs quote: ", label));
            // router holds nothing afterward
            assertEq(IERC20(tokenOut).balanceOf(address(router)), 0, "out residual");
            assertEq(IERC20(WPLS).balanceOf(address(router)), 0, "wpls residual");

            emit log_named_string("PASS", label);
            emit log_named_uint("  amountIn(PLS)", amountIn / 1e18);
            emit log_named_uint("  expected", expected);
            emit log_named_uint("  realized", realized);
            passed++;
        }
        assertEq(passed, count, "all real routes execute ~ quote");
    }
}
